import Image from "next/image";
import { WalletConnect } from "@/components/WalletConnect";
import { LockInteraction } from "@/components/LockInteraction";

export default function Home() {
  return (
    <div className="flex min-h-screen flex-col items-center justify-center bg-zinc-950 font-sans text-zinc-100 selection:bg-indigo-500/30">
      {/* Background Gradient Orbs */}
      <div className="fixed inset-0 overflow-hidden -z-10">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] rounded-full bg-indigo-500/10 blur-[120px]" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[40%] h-[40%] rounded-full bg-emerald-500/10 blur-[120px]" />
      </div>

      <main className="flex w-full max-w-4xl flex-col gap-12 py-20 px-6">
        <header className="flex flex-col gap-4 text-center sm:text-left">
          <div className="flex items-center gap-3 justify-center sm:justify-start">
            <div className="p-3 bg-zinc-900 rounded-2xl border border-zinc-800 shadow-xl">
              <Image
                className="dark:invert"
                src="/next.svg"
                alt="Next.js logo"
                width={80}
                height={16}
                priority
              />
            </div>
            <span className="text-zinc-500 font-medium">+</span>
            <div className="px-4 py-2 bg-indigo-600/10 rounded-full border border-indigo-500/20">
              <span className="text-xs font-bold text-indigo-400 uppercase tracking-widest">Viem + Wagmi</span>
            </div>
          </div>

          <h1 className="text-4xl md:text-6xl font-bold tracking-tight text-white leading-[1.1]">
            LHC Blockchain <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-emerald-400">
              Infrastructure
            </span>
          </h1>
          <p className="max-w-lg text-lg text-zinc-400 leading-relaxed">
            Your monorepo is now equipped with a professional blockchain bridge.
            Connect your wallet to interact with your smart contracts directly from this interface.
          </p>
        </header>

        <section className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <WalletConnect />

          <div className="flex flex-col gap-4 p-8 bg-zinc-900/50 rounded-3xl border border-white/5 backdrop-blur-sm">
            <h3 className="text-xl font-bold text-white">Project Status</h3>
            <ul className="flex flex-col gap-3">
              {[
                { label: 'API Service', status: 'Online', color: 'text-emerald-400' },
                { label: 'Smart Contracts', status: 'Deployed (Local)', color: 'text-indigo-400' },
                { label: 'Frontend Bridge', status: 'Active', color: 'text-emerald-400' },
              ].map((item) => (
                <li key={item.label} className="flex items-center justify-between py-2 border-b border-white/5">
                  <span className="text-zinc-500 text-sm">{item.label}</span>
                  <span className={`text-xs font-bold font-mono ${item.color}`}>{item.status}</span>
                </li>
              ))}
            </ul>
          </div>
        </section>

        <section>
          <LockInteraction />
        </section>

        <footer className="mt-12 pt-8 border-t border-white/5 text-center sm:text-left">
          <p className="text-zinc-600 text-sm">
            Generated by Antigravity Integration Engine
          </p>
        </footer>
      </main>
    </div>
  );
}
